import json
from pathlib import Path

BASE_PATH = Path(__file__).resolve().parent.parent
DATA_PATH = BASE_PATH / "data"

REFLEX_FILE = DATA_PATH / "evolution_reflex_signal.json"
INTELLIGENCE_FILE = DATA_PATH / "evolution_intelligence_state.json"
NARRATIVE_FILE = DATA_PATH / "evolution_narrative.txt"


def load_json(path):

    if not path.exists():
        return None

    with open(path) as f:
        return json.load(f)


def build_narrative(reflex, intelligence):

    if reflex is None:
        return "Organism sensory layer incomplete."

    signal = reflex["reflex_signal"]

    regime = "unknown"
    posture = "unknown"

    if intelligence:
        regime = intelligence.get("regime", "unknown")
        posture = intelligence.get("strategic_posture", "unknown")

    narrative = []

    narrative.append("Bitcoin Organism - Evolution Narrative")
    narrative.append("--------------------------------------")
    narrative.append("")
    narrative.append("Current regime: " + regime)
    narrative.append("Strategic posture: " + posture)
    narrative.append("Reflex signal: " + signal)
    narrative.append("")

    if signal == "Critical Expansion":

        narrative.append(
        "The organism is experiencing extreme expansion pressure. "
        "Historically this often precedes volatility spikes or regime transitions."
        )

    elif signal == "Deep Compression":

        narrative.append(
        "The organism is under deep compression. "
        "Such states frequently appear during accumulation or systemic stress."
        )

    elif signal == "Rapid Expansion":

        narrative.append(
        "Expansion pressure is accelerating. "
        "Momentum may increase if structural tension remains contained."
        )

    elif signal == "Rapid Contraction":

        narrative.append(
        "The system is contracting rapidly. "
        "Risk management conditions may dominate short-term evolution."
        )

    else:

        narrative.append(
        "The organism currently shows stable evolutionary dynamics. "
        "No immediate structural instability is detected."
        )

    narrative.append("")
    narrative.append("Narrative generated by the Bitcoin Organism interpretative layer.")

    return "\n".join(narrative)


def save_narrative(text):

    with open(NARRATIVE_FILE, "w") as f:
        f.write(text)


def main():

    print("\nBitcoin Organism - Evolution Narrative Engine")
    print("--------------------------------------------------")

    reflex = load_json(REFLEX_FILE)
    intelligence = load_json(INTELLIGENCE_FILE)

    narrative = build_narrative(reflex, intelligence)

    save_narrative(narrative)

    print("Narrative generated:")
    print(NARRATIVE_FILE)


if __name__ == "__main__":
    main()
